### ISSUE TITLE
3.1.1: "Code Error" when dealing Venom damage

### ISSUE THREAD

**Issue by usrbincat** [joeribakker/cantrip#12]
I was fighting Yaga and I played venom, then rest, ended my turn. She played a bunch of cards, some of them might have interacted with each other, I can't quite remember. Then it was my turn again, I did Blood Rites and Rest. When she took venom damage at the beginning of her turn, I got this "Code Error":

![cantrip bug 2](https://user-images.githubusercontent.com/4317605/100595087-160d1d80-32c0-11eb-8e88-20fea23168e7.png)

This was what the game looked like:

![cantrip bug 1](https://user-images.githubusercontent.com/4317605/100595153-291fed80-32c0-11eb-9582-764a5d6e8986.png)

(Bugs aside, I really like the new UI updates!)

**Comment by bakkerjoeri** [comment]
Thanks a lot for reporting! Looks like I oopsied somewhere in the Waning card code. It _might_ be fixed in 3.2.0 since I changed Waning's behaviour, but I'll double check.

**Comment by bakkerjoeri** [comment]
Possibly the same bug showing up in 3.2.0: https://itch.io/post/2340463

**Comment by bakkerjoeri** [comment]
Fixed it in 61c966025e7ab168834853226decf72d0514ab79. It'll be in the next build. 

Turns out both the game would crash when either waning and lunar surge effect ended after cards they influenced had been destroyed. When reversing the cost change, there was no check whether the card still existed.
